//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server3C_102.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateMahasiswa", ReplyAction="http://tempuri.org/IService1/UpdateMahasiswaResponse")]
        string UpdateMahasiswa(string nim, string nama, string prodi, string angkatan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateMahasiswa", ReplyAction="http://tempuri.org/IService1/UpdateMahasiswaResponse")]
        System.Threading.Tasks.Task<string> UpdateMahasiswaAsync(string nim, string nama, string prodi, string angkatan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteByNIM", ReplyAction="http://tempuri.org/IService1/DeleteByNIMResponse")]
        string DeleteByNIM(string nim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteByNIM", ReplyAction="http://tempuri.org/IService1/DeleteByNIMResponse")]
        System.Threading.Tasks.Task<string> DeleteByNIMAsync(string nim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CountMahasiswa", ReplyAction="http://tempuri.org/IService1/CountMahasiswaResponse")]
        string CountMahasiswa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CountMahasiswa", ReplyAction="http://tempuri.org/IService1/CountMahasiswaResponse")]
        System.Threading.Tasks.Task<string> CountMahasiswaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllMahasiswa", ReplyAction="http://tempuri.org/IService1/GetAllMahasiswaResponse")]
        Service3B_102.Mahasiswa[] GetAllMahasiswa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllMahasiswa", ReplyAction="http://tempuri.org/IService1/GetAllMahasiswaResponse")]
        System.Threading.Tasks.Task<Service3B_102.Mahasiswa[]> GetAllMahasiswaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Server3C_102.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Server3C_102.ServiceReference1.IService1>, Server3C_102.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string UpdateMahasiswa(string nim, string nama, string prodi, string angkatan) {
            return base.Channel.UpdateMahasiswa(nim, nama, prodi, angkatan);
        }
        
        public System.Threading.Tasks.Task<string> UpdateMahasiswaAsync(string nim, string nama, string prodi, string angkatan) {
            return base.Channel.UpdateMahasiswaAsync(nim, nama, prodi, angkatan);
        }
        
        public string DeleteByNIM(string nim) {
            return base.Channel.DeleteByNIM(nim);
        }
        
        public System.Threading.Tasks.Task<string> DeleteByNIMAsync(string nim) {
            return base.Channel.DeleteByNIMAsync(nim);
        }
        
        public string CountMahasiswa() {
            return base.Channel.CountMahasiswa();
        }
        
        public System.Threading.Tasks.Task<string> CountMahasiswaAsync() {
            return base.Channel.CountMahasiswaAsync();
        }
        
        public Service3B_102.Mahasiswa[] GetAllMahasiswa() {
            return base.Channel.GetAllMahasiswa();
        }
        
        public System.Threading.Tasks.Task<Service3B_102.Mahasiswa[]> GetAllMahasiswaAsync() {
            return base.Channel.GetAllMahasiswaAsync();
        }
    }
}
